### ISSUE TITLE
Poster Fair Demo Use Cases

### ISSUE THREAD

**Issue by DerekStride** [GraphQL-Query-Planner/webscale#46]
- [x] N+1s
- [x] Full table scan
- [x] indexed
- [x] indexed with additional filtering
  - need 2 where conditions for this (e.g. WHERE id < 100 AND id > 10 AND last_name = "Smith")
  - make sure more than one result is returned
- [ ] Multiple datastores (pg and mysql)
  - [ ] Gem bug fixed
- [x] Using an un optimal index (use IGNORE INDEX here)

**Comment by justinkrol** [comment]
#### Query examples

These queries show examples of problems (or non-problems) that can be identified with the graphql-analyzer.
**Note: id values will need to be changed**

### N+1
**Description**
We can select the posts that a user has made.  This will generate N+1 db queries as it loads information about each receiver.
```graphql
{
  node(id: "gid://webscale/User/1") {
    id
    ...on User {
      posts {
        id
        receiver {
          id
          first_name
          last_name
        }
        body
      }
    }
  }
}
```

### Optimized (removed N+1 with a batch loader)
**Description**
We can also select the posts on a user's wall, and in this case, we've implemented a batch loader to load the authors of the individual posts.
```graphql
{
  node(id: "gid://webscale/User/1") {
    id
    ...on User {
      wall {
        id
        author {
          id
          first_name
          last_name
        }
        body
      }
    }
  }
}
```

### Indexed
**Description**
If we want to select the comments that exist for a specific post, we make this query.
Since comments are indexed on the `content_id` (post id in this case), we get an indexed search
```graphql
{
  node(id: "gid://webscale/Post/1") {
    id
    ...on Post {
      comments {
        id
      }
    }
  }
}
```

**Description**
Here is another indexed query, searching for users with a specific last name. 
The query below which searches on last name will only search 1 row, since the `users` table has an index for `last_name`.
```graphql
{
  users(last_name: "Hane") {
    edges{
      node {
        id
        first_name
        last_name
        email
      }
    }
  }
}
```

### Non-Indexed (Full Table Scan)
**Description**
Perhaps we add to the GraphQL schema the ability to also query for users with a certain first name.
If we forget to add an index on the `users` table for `first_name`, we'll get a full table scan.
```graphql
{
  users(first_name: "Roderick") {
    edges{
      node {
        id
        first_name
        last_name
        email
      }
    }
  }
}
```


### Indexed with additional filtering
**Description**
Select posts for a specific receiver within a certain range of IDs.
```graphql
{
  node(id:"gid://webscale/User/1") {
    id
    ...on User {
      wall(min_id: 1, max_id: 200) {
        id
      }
    }
  }
}
```

### Unoptimal index
**Description**
Find a like on a specific post by a specific user
```graphql
{
  likes(content_id: "gid://webscale/Post/11", content_type: "Post", user_id: "gid://webscale/User/1") {
    edges{
      node {
        id
        user {
          id
        }
      }
    }
  }
}
```

**Comment by DerekStride** [comment]
This might be a better N+1 example. It has both an unoptimized and batch loaded field.

```graphql
query {
  users(first: 30) {
    edges {
      node {
        id
        first_name
        last_name
        wall { # Batched (no N+1s)
          id
        }
        posts { # Unoptimized (N+1s)
          id
        }
      }
    }
  }
}
```

**Comment by justinkrol** [comment]
I've updated my previous comment with an updated N+1 example, and am removing the batching on the `wall` field of `UserType`.

**Comment by DerekStride** [comment]
```
################### N+1s ###################
# {
#   node(id: "gid://webscale/User/1") {
#     id
#     ...on User {
#       posts {
#         id
#         receiver { # N+1
#           id
#         }
#       }
#     }
#   }
# }

################### Fixed N+1s ###################
# {
#   node(id: "gid://webscale/User/1") {
#     id
#     ...on User {
#       wall {
#         id
#         author { # N+1
#           id
#         }
#       }
#     }
#   }
# }

################### Indexed ###################
# {
#   users(last_name: "Hane") {
#     edges{
#       node {
#         id
#         first_name
#         last_name
#         email
#       }
#     }
#   }
# }

################### Non-indexed ###################

# {
#   users(first_name: "Roderick") {
#     edges{
#       node {
#         id
#         first_name
#         last_name
#         email
#       }
#     }
#   }
# }

################### Indexed (w/ FileSort) ###################
# {
#   node(id:"gid://webscale/User/1") {
#     id
#     ...on User {
#       wall(min_id: 1, max_id: 200) {
#         id
#       }
#     }
#   }
# }

################### Wrong Index ###################
# {
#   likes(content_id: "gid://webscale/Post/81", content_type: "Post", user_id: "gid://webscale/User/1") {
#     edges{
#       node {
#         id
#         user {
#           id
#         }
#       }
#     }
#   }
# }

################### ES Query ###################
# {
#   search(query: "drizzle") {
#     id
#     index
#     score
#     type
#   }
# }
```

**Comment by DerekStride** [comment]
👍
